version: "3.9"
networks: 
  message-service-network:
    driver: bridge
services:
  client-writer:
    image: clientwriter1
    networks:
      - message-service-network
    ports:
      - 8282:8080  

  client-sender:
    image: clientsenderimage6
    networks:
      - message-service-network
    ports:
      - 8181:8080  

  client-history:
    image: clienthistory
    networks:
      - message-service-network
    ports:
      - 8383:8080 
    
  
  webservice:
    container_name: web-server-container
    build:
      context: .
      dockerfile: ./KoshelekWebServer/Dockerfile
    image: dotnetmonster/web-server-dnm
    ports:
      - 25545:8080
    networks:
      - message-service-network
    depends_on:
      - postgres_db
  postgres_db:
    command: postgres -c listen_addresses='*'
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: koshelek-db
    ports:
      - 5432:5001  
    networks:
      - message-service-network
    volumes:
      - postgres-data:/var/lib/data
volumes:
  postgres-data: